// <auto-generated />
using System;
using HeroesMatchTracker.Infrastructure.Database.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HeroesMatchTracker.Infrastructure.Database.Migrations.HeroesReplays
{
    [DbContext(typeof(HeroesReplaysDbContext))]
    [Migration("20200711043321_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayAllHotsPlayer", b =>
                {
                    b.Property<long>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattleNetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattleNetRegionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattleNetSubId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BattleNetTId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BattleTagName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeenBefore")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Seen")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId");

                    b.ToTable("ReplayAllHotsPlayers");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayHotsApiUpload", b =>
                {
                    b.Property<long>("ReplaysHotsApiUploadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReplayFileTimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("ReplayId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReplaysHotsApiUploadId");

                    b.HasIndex("ReplayId");

                    b.ToTable("ReplayHotsApiUploads");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayMatch", b =>
                {
                    b.Property<long>("ReplayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(260);

                    b.Property<int?>("Frames")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameSpeed")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGameEventsParsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<long?>("RandomValue")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReplayBuild")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReplayLengthTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplayVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<string>("TeamSize")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("ReplayId");

                    b.ToTable("Replays");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayMatchAward", b =>
                {
                    b.Property<long>("MatchAwardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Award")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReplayId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchAwardId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ReplayId");

                    b.ToTable("ReplayMatchAwards");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayMatchDraftPick", b =>
                {
                    b.Property<long>("DraftPickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeroSelected")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PickType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerSlotId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReplayId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DraftPickId");

                    b.HasIndex("ReplayId");

                    b.ToTable("ReplayMatchDraftPicks");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayMatchMessage", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageEventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageTarget")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<long>("ReplayId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TimeStampTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("MessageId");

                    b.HasIndex("ReplayId");

                    b.ToTable("ReplayMatchMessages");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayMatchPlayer", b =>
                {
                    b.Property<long>("MatchPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<int>("CharacterLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<int?>("Handicap")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasActiveBoost")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAutoSelect")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBlizzardStaff")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSilenced")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVoiceSilenced")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MountAndMountTint")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<int>("PartySize")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PartyValue")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReplayId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkinAndSkinTint")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<int?>("Team")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchPlayerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ReplayId");

                    b.ToTable("ReplayMatchPlayers");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayMatchPlayerScoreResult", b =>
                {
                    b.Property<long>("MatchPlayerScoreResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Assists")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreepDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DamageTaken")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Deaths")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExperienceContribution")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Healing")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeroDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MercCampCaptures")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MetaExperience")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinionDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PhysicalDamage")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReplayId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelfHealing")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SiegeDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SoloKills")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpellDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StructureDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SummonDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TakeDowns")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TimeCCdEnemyHeroes")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TimeSpentDeadTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TownKills")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WatchTowerCaptures")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchPlayerScoreResultId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ReplayId");

                    b.ToTable("ReplayMatchPlayerScoreResults");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayMatchPlayerTalent", b =>
                {
                    b.Property<long>("MatchPlayerTalentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReplayId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TalentId1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TalentId10")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TalentId13")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TalentId16")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TalentId20")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TalentId4")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TalentId7")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TalentName1")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(75);

                    b.Property<string>("TalentName10")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(75);

                    b.Property<string>("TalentName13")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(75);

                    b.Property<string>("TalentName16")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(75);

                    b.Property<string>("TalentName20")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(75);

                    b.Property<string>("TalentName4")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(75);

                    b.Property<string>("TalentName7")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(75);

                    b.Property<long?>("TimeSpanSelected10Ticks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TimeSpanSelected13Ticks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TimeSpanSelected16Ticks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TimeSpanSelected1Ticks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TimeSpanSelected20Ticks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TimeSpanSelected4Ticks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TimeSpanSelected7Ticks")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchPlayerTalentId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ReplayId");

                    b.ToTable("ReplayMatchPlayerTalents");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayMatchTeamBan", b =>
                {
                    b.Property<long>("ReplayId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Team0Ban0")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("Team0Ban1")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("Team0Ban2")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("Team1Ban0")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("Team1Ban1")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("Team1Ban2")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("ReplayId");

                    b.ToTable("ReplayMatchTeamBans");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayMatchTeamExperience", b =>
                {
                    b.Property<long>("MatchTeamExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReplayId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Team0CreepXP")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Team0HeroXP")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Team0MinionXP")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Team0StructureXP")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Team0TeamLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Team0TrickleXP")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Team1CreepXP")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Team1HeroXP")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Team1MinionXP")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Team1StructureXP")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Team1TeamLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Team1TrickleXP")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TimeTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchTeamExperienceId");

                    b.HasIndex("ReplayId");

                    b.ToTable("ReplayMatchTeamExperiences");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayMatchTeamLevel", b =>
                {
                    b.Property<long>("MatchTeamLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReplayId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Team0Level")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Team1Level")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TeamTime0Ticks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TeamTime1Ticks")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchTeamLevelId");

                    b.HasIndex("ReplayId");

                    b.ToTable("ReplayMatchTeamLevels");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayMatchTeamObjective", b =>
                {
                    b.Property<long>("MatchTeamTeamObjectiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReplayId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Team")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamObjectiveType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(255);

                    b.Property<long?>("TimeStampTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchTeamTeamObjectiveId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ReplayId");

                    b.ToTable("ReplayMatchTeamObjectives");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayRenamedPlayer", b =>
                {
                    b.Property<long>("RenamedPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattleNetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattleNetRegionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattleNetSubId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BattleNetTId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BattleTagName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RenamedPlayerId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("ReplayRenamedPlayers");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayHotsApiUpload", b =>
                {
                    b.HasOne("HeroesMatchTracker.Core.ModelsDb.ReplayMatch", "Replay")
                        .WithMany("ReplayHotsApiUploads")
                        .HasForeignKey("ReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayMatchAward", b =>
                {
                    b.HasOne("HeroesMatchTracker.Core.ModelsDb.ReplayAllHotsPlayer", "ReplayAllHotsPlayer")
                        .WithMany("ReplayMatchAwards")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeroesMatchTracker.Core.ModelsDb.ReplayMatch", "Replay")
                        .WithMany("ReplayMatchAwards")
                        .HasForeignKey("ReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayMatchDraftPick", b =>
                {
                    b.HasOne("HeroesMatchTracker.Core.ModelsDb.ReplayMatch", "Replay")
                        .WithMany("ReplayMatchDraftPicks")
                        .HasForeignKey("ReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayMatchMessage", b =>
                {
                    b.HasOne("HeroesMatchTracker.Core.ModelsDb.ReplayMatch", "Replay")
                        .WithMany("ReplayMatchMessages")
                        .HasForeignKey("ReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayMatchPlayer", b =>
                {
                    b.HasOne("HeroesMatchTracker.Core.ModelsDb.ReplayAllHotsPlayer", "ReplayAllHotsPlayer")
                        .WithMany("ReplayMatchPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeroesMatchTracker.Core.ModelsDb.ReplayMatch", "Replay")
                        .WithMany("ReplayMatchPlayers")
                        .HasForeignKey("ReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayMatchPlayerScoreResult", b =>
                {
                    b.HasOne("HeroesMatchTracker.Core.ModelsDb.ReplayAllHotsPlayer", "ReplayAllHotsPlayer")
                        .WithMany("ReplayMatchPlayerScoreResults")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeroesMatchTracker.Core.ModelsDb.ReplayMatch", "Replay")
                        .WithMany("ReplayMatchPlayerScoreResults")
                        .HasForeignKey("ReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayMatchPlayerTalent", b =>
                {
                    b.HasOne("HeroesMatchTracker.Core.ModelsDb.ReplayAllHotsPlayer", "ReplayAllHotsPlayer")
                        .WithMany("ReplayMatchPlayerTalents")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeroesMatchTracker.Core.ModelsDb.ReplayMatch", "Replay")
                        .WithMany("ReplayMatchPlayerTalents")
                        .HasForeignKey("ReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayMatchTeamBan", b =>
                {
                    b.HasOne("HeroesMatchTracker.Core.ModelsDb.ReplayMatch", "Replay")
                        .WithOne("ReplayMatchTeamBans")
                        .HasForeignKey("HeroesMatchTracker.Core.ModelsDb.ReplayMatchTeamBan", "ReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayMatchTeamExperience", b =>
                {
                    b.HasOne("HeroesMatchTracker.Core.ModelsDb.ReplayMatch", "Replay")
                        .WithMany("ReplayMatchTeamExperiences")
                        .HasForeignKey("ReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayMatchTeamLevel", b =>
                {
                    b.HasOne("HeroesMatchTracker.Core.ModelsDb.ReplayMatch", "Replay")
                        .WithMany("ReplayMatchTeamLevels")
                        .HasForeignKey("ReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayMatchTeamObjective", b =>
                {
                    b.HasOne("HeroesMatchTracker.Core.ModelsDb.ReplayAllHotsPlayer", "ReplayAllHotsPlayer")
                        .WithMany("ReplayMatchTeamObjectives")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HeroesMatchTracker.Core.ModelsDb.ReplayMatch", "Replay")
                        .WithMany("ReplayMatchTeamObjectives")
                        .HasForeignKey("ReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.ModelsDb.ReplayRenamedPlayer", b =>
                {
                    b.HasOne("HeroesMatchTracker.Core.ModelsDb.ReplayAllHotsPlayer", "ReplayAllHotsPlayer")
                        .WithOne("ReplayRenamedPlayer")
                        .HasForeignKey("HeroesMatchTracker.Core.ModelsDb.ReplayRenamedPlayer", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
