// <auto-generated />
using System;
using HeroesMatchTracker.Infrastructure.Database.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HeroesMatchTracker.Infrastructure.Database.Migrations.HeroesReplays
{
    [DbContext(typeof(HeroesReplaysDbContext))]
    [Migration("20210102222148_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayMatch", b =>
                {
                    b.Property<long>("ReplayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasAI")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasObservers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MapId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("OwnerPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RandomValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Region")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplayFilePath")
                        .HasColumnType("TEXT");

                    b.Property<long>("ReplayLengthTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplayVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("WinningTeam")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReplayId");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("OwnerPlayerId");

                    b.ToTable("Replays");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayMatchPlayer", b =>
                {
                    b.Property<long>("MatchPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Difficulty")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasActiveBoost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeroAttributeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HeroLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeroName")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroUnitId")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsAutoSelect")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBlizzardStaff")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSilenced")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVoiceSilenced")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsWinner")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PartySize")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PartyValue")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReplayId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Team")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchPlayerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ReplayId");

                    b.ToTable("ReplayMatchPlayers");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayMatchPlayerLoadout", b =>
                {
                    b.Property<long>("MatchPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnnouncerPackAttributeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnnouncerPackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BannerAttributeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BannerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MountAndMountTintAttributeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MountAndMountTintId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkinAndSkinTintAttributeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkinAndSkinTintId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SprayAttributeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SprayId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoiceLineAttributeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoiceLineId")
                        .HasColumnType("TEXT");

                    b.HasKey("MatchPlayerId");

                    b.ToTable("ReplayMatchPlayerLoadout");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayMatchPlayerScoreResult", b =>
                {
                    b.Property<long>("MatchPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Assists")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClutchHealsPerformed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreepDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DamageSoaked")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DamageTaken")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Deaths")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EscapesPerformed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExperienceContribution")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Healing")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeroDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HighestKillStreak")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MercCampCaptures")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MetaExperience")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinionDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinionKills")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Multikill")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OnFireTimeonFireTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OutnumberedDeaths")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PhysicalDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProtectionGivenToAllies")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RegenGlobes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelfHealing")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SiegeDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SoloKills")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpellDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StructureDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SummonDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TakeDowns")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamfightDamageTaken")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamfightEscapesPerformed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamfightHealingDone")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamfightHeroDamage")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TimeCCdEnemyHeroesTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TimeRootingEnemyHeroesTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TimeSpentDeadTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TimeStunningEnemyHeroesTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TownKills")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VengeancesPerformed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WatchTowerCaptures")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchPlayerId");

                    b.ToTable("ReplayMatchPlayerScoreResults");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayMatchPlayerTalent", b =>
                {
                    b.Property<long>("MatchPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TalentId1")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TalentId10")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TalentId13")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TalentId16")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TalentId20")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TalentId4")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TalentId7")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TimeSpanSelected10Ticks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TimeSpanSelected13Ticks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TimeSpanSelected16Ticks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TimeSpanSelected1Ticks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TimeSpanSelected20Ticks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TimeSpanSelected4Ticks")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TimeSpanSelected7Ticks")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchPlayerId");

                    b.ToTable("ReplayMatchPlayerTalents");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayOldPlayerInfo", b =>
                {
                    b.Property<long>("ReplayOldPlayerInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BattleTagName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReplayOldPlayerInfoId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ReplayOldPlayerInfos");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayPlayer", b =>
                {
                    b.Property<long>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BattleTagName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeenBefore")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Seen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortcutId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.ToTable("ReplayPlayers");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayPlayerToon", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProgramId")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<int>("Realm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Region")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId");

                    b.HasIndex("Region", "ProgramId", "Realm", "Id");

                    b.ToTable("ReplayPlayerToons");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ServerReplayUpload", b =>
                {
                    b.Property<long>("ServerReplayUploadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReplayId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerName")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UploadedTimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("ServerReplayUploadId");

                    b.HasIndex("ReplayId");

                    b.ToTable("ServerReplayUploads");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayMatch", b =>
                {
                    b.HasOne("HeroesMatchTracker.Core.Entities.ReplayPlayer", "OwnerReplayPlayer")
                        .WithMany("OwnerReplayMatches")
                        .HasForeignKey("OwnerPlayerId");

                    b.Navigation("OwnerReplayPlayer");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayMatchPlayer", b =>
                {
                    b.HasOne("HeroesMatchTracker.Core.Entities.ReplayPlayer", "ReplayPlayer")
                        .WithMany("ReplayMatchPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeroesMatchTracker.Core.Entities.ReplayMatch", "Replay")
                        .WithMany("ReplayMatchPlayers")
                        .HasForeignKey("ReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Replay");

                    b.Navigation("ReplayPlayer");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayMatchPlayerLoadout", b =>
                {
                    b.HasOne("HeroesMatchTracker.Core.Entities.ReplayMatchPlayer", "ReplayMatchPlayer")
                        .WithOne("ReplayMatchPlayerLoadout")
                        .HasForeignKey("HeroesMatchTracker.Core.Entities.ReplayMatchPlayerLoadout", "MatchPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReplayMatchPlayer");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayMatchPlayerScoreResult", b =>
                {
                    b.HasOne("HeroesMatchTracker.Core.Entities.ReplayMatchPlayer", "ReplayMatchPlayer")
                        .WithOne("ReplayMatchPlayerScoreResult")
                        .HasForeignKey("HeroesMatchTracker.Core.Entities.ReplayMatchPlayerScoreResult", "MatchPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReplayMatchPlayer");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayMatchPlayerTalent", b =>
                {
                    b.HasOne("HeroesMatchTracker.Core.Entities.ReplayMatchPlayer", "ReplayMatchPlayer")
                        .WithOne("ReplayMatchPlayerTalent")
                        .HasForeignKey("HeroesMatchTracker.Core.Entities.ReplayMatchPlayerTalent", "MatchPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReplayMatchPlayer");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayOldPlayerInfo", b =>
                {
                    b.HasOne("HeroesMatchTracker.Core.Entities.ReplayPlayer", "ReplayPlayer")
                        .WithMany("ReplayOldPlayerInfos")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReplayPlayer");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayPlayerToon", b =>
                {
                    b.HasOne("HeroesMatchTracker.Core.Entities.ReplayPlayer", "ReplayPlayer")
                        .WithOne("ReplayPlayerToon")
                        .HasForeignKey("HeroesMatchTracker.Core.Entities.ReplayPlayerToon", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReplayPlayer");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ServerReplayUpload", b =>
                {
                    b.HasOne("HeroesMatchTracker.Core.Entities.ReplayMatch", "Replay")
                        .WithMany("ServerReplayUploads")
                        .HasForeignKey("ReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Replay");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayMatch", b =>
                {
                    b.Navigation("ReplayMatchPlayers");

                    b.Navigation("ServerReplayUploads");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayMatchPlayer", b =>
                {
                    b.Navigation("ReplayMatchPlayerLoadout");

                    b.Navigation("ReplayMatchPlayerScoreResult");

                    b.Navigation("ReplayMatchPlayerTalent");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayPlayer", b =>
                {
                    b.Navigation("OwnerReplayMatches");

                    b.Navigation("ReplayMatchPlayers");

                    b.Navigation("ReplayOldPlayerInfos");

                    b.Navigation("ReplayPlayerToon");
                });
#pragma warning restore 612, 618
        }
    }
}
