// <auto-generated />
using System;
using HeroesMatchTracker.Infrastructure.Database.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HeroesMatchTracker.Infrastructure.Database.Migrations
{
    [DbContext(typeof(HeroesReplaysDbContext))]
    [Migration("20201003163807_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-rc.1.20451.13");

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayMatch", b =>
                {
                    b.Property<long>("ReplayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<int>("GameMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MapId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long?>("RandomValue")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReplayLengthTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplayVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("ReplayId");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.ToTable("Replays");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayMatchPlayer", b =>
                {
                    b.Property<long>("MatchPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BattleTagName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasActiveBoost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeroId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HeroLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeroName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsAutoSelect")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBlizzardStaff")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSilenced")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVoiceSilenced")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsWinner")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PartySize")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PartyValue")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReplayId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ReplayPlayerPlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Team")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchPlayerId");

                    b.HasIndex("ReplayId");

                    b.HasIndex("ReplayPlayerPlayerId");

                    b.ToTable("ReplayMatchPlayers");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayOldPlayerInfo", b =>
                {
                    b.Property<long>("ReplayOldPlayerInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BattleTagName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ReplayPlayerPlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReplayOldPlayerInfoId");

                    b.HasIndex("ReplayPlayerPlayerId");

                    b.ToTable("ReplayOldPlayerInfos");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayPlayer", b =>
                {
                    b.Property<long>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BattleTagName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeenBefore")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Seen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortcutId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.ToTable("ReplayPlayers");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayPlayerToon", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProgramId")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<int>("Realm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Region")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId");

                    b.HasIndex("Region", "ProgramId", "Realm", "Id");

                    b.ToTable("ReplayPlayerToons");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ServerReplayUpload", b =>
                {
                    b.Property<long>("ServerReplayUploadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReplayId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerName")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UploadedTimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("ServerReplayUploadId");

                    b.HasIndex("ReplayId");

                    b.ToTable("ServerReplayUploads");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayMatchPlayer", b =>
                {
                    b.HasOne("HeroesMatchTracker.Core.Entities.ReplayMatch", "Replay")
                        .WithMany("ReplayMatchPlayers")
                        .HasForeignKey("ReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeroesMatchTracker.Core.Entities.ReplayPlayer", "ReplayPlayer")
                        .WithMany("ReplayMatchPlayers")
                        .HasForeignKey("ReplayPlayerPlayerId");

                    b.Navigation("Replay");

                    b.Navigation("ReplayPlayer");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayOldPlayerInfo", b =>
                {
                    b.HasOne("HeroesMatchTracker.Core.Entities.ReplayPlayer", "ReplayPlayer")
                        .WithMany("ReplayOldPlayerInfos")
                        .HasForeignKey("ReplayPlayerPlayerId");

                    b.Navigation("ReplayPlayer");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayPlayerToon", b =>
                {
                    b.HasOne("HeroesMatchTracker.Core.Entities.ReplayPlayer", "ReplayPlayer")
                        .WithOne("ReplayPlayerToon")
                        .HasForeignKey("HeroesMatchTracker.Core.Entities.ReplayPlayerToon", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReplayPlayer");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ServerReplayUpload", b =>
                {
                    b.HasOne("HeroesMatchTracker.Core.Entities.ReplayMatch", "Replay")
                        .WithMany("ServerReplayUploads")
                        .HasForeignKey("ReplayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Replay");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayMatch", b =>
                {
                    b.Navigation("ReplayMatchPlayers");

                    b.Navigation("ServerReplayUploads");
                });

            modelBuilder.Entity("HeroesMatchTracker.Core.Entities.ReplayPlayer", b =>
                {
                    b.Navigation("ReplayMatchPlayers");

                    b.Navigation("ReplayOldPlayerInfos");

                    b.Navigation("ReplayPlayerToon");
                });
#pragma warning restore 612, 618
        }
    }
}
