namespace Heroes.Icons.Models
{
    public enum OtherIcon
    {
        Silence,
        VoiceSilence,
        Quest,
        LongarrowLeftDisabled,
        LongarrowLeftDown,
        LongarrowLeftHover,
        LongarrowLeftNormal,
        LongarrowRightDisabled,
        LongarrowRightDown,
        LongarrowRightHover,
        LongarrowRightNormal,
        TalentAvailable,
        TalentUnavailable,
        StatusResistShieldDefault,
        StatusResistShieldPhysical,
        StatusResistShieldSpell,
        UpgradeQuest,
        FilterAssassin,
        FilterMulticlass,
        FilterSpecialist,
        FilterSupport,
        FilterWarrior,
        Kills,
        Assist,
        Death,
        KillsBlue,
        KillsRed,
    }
}
